name: Animation Generator

on:
  schedule:
    - cron: "*/5 * * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3 # Versão estável
        with:
          github_user_name: AnaPaula-Monteiro
          
          # A cor é definida aqui
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=pink
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push new files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
