name: Animation Generator

on:
  schedule:
    # Roda a cada 5 minutos
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: AnaPaula-Monteiro

          # Caminhos de saída
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

          # 🎨 Cores personalizadas
          color_snake: "#FFC0CB,#FF69B4" # rosa claro e rosa escuro
          color_dots: "#333333,#555555,#777777,#999999,#BBBBBB" # tons de cinza
          color_background: "#000000" # fundo preto

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
