name: Generate Snake Animation

on:
  schedule:
  - cron: "*/5 * * * *" 
  workflow_dispatch:
  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
        github_user_name: AnaPaula-Monteiro
color_snake: "#FFC0CB"
color_dots: "#f0f0f0,#f5e0e0,#fbc0c0,#ff9c9c,#ff6a6a"
name: Generate Snake Animation

on:
  schedule:
    # O intervalo mínimo permitido no GitHub Actions é de 5 minutos.
    # Este cron rodará a cada 5 minutos.
    - cron: "*/5 * * * *" 
  workflow_dispatch:
    # Permite executar o workflow manualmente na aba "Actions".

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          # [OBRIGATÓRIO] Seu nome de usuário do GitHub.
          github_user_name: SEU_NOME_DE_USUARIO_AQUI
          
          # Define a cor da cobrinha como ROSA CLARO (#FFC0CB)
          color_snake: "#FFC0CB" 
          
          # [OPCIONAL] Se quiser que os pontos de contribuição também tenham um tema de cor rosa claro:
          # color_dots: "#f0f0f0,#f5e0e0,#fbc0c0,#ff9c9c,#ff6a6a"
          
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push new files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
